# Generated by Django 2.2.28 on 2026-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', '-created')},
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Maintain', 'Maintain')], default='Maintain', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
