# Generated by Django 2.2.28 on 2026-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Product-images/'),
        ),
    ]
