# Generated by Django 2.2.28 on 2026-07-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260703_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealth',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
